import type { Metadata } from "next";
import { Inter, Inria_Serif } from "next/font/google";
import "@/styles/globals.css";
import { MusicPlayerProvider } from "@/providers/MusicPlayer";
import ReduxProvider from "@/providers/ReduxProvider";
import GoogleOAuthProviderWrapper from "@/providers/GoogleOAuthProvider";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/features/auth/provider/AuthProvider";

const sans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: "variable",
});

const serif = Inria_Serif({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Cian Intl",
  description: "Generated by Cian Intl",
};

export default function RootLayout({
  children,
}: Readonly<{
  marketing?: React.ReactNode;
  children?: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${sans.variable} ${serif.variable} antialiased`}>
        <AuthProvider>
          {/* {marketing} */}
          <GoogleOAuthProviderWrapper>
            <ReduxProvider>
              <MusicPlayerProvider>
                {children}
                <Toaster
                  position="top-center"
                  toastOptions={{
                    style: {
                      background: "#18181b",
                      color: "#f3f4f6",
                      border: "1px solid #27272a",
                      boxShadow: "0 4px 24px 0 #00000080",
                      fontSize: "1rem",
                    },
                    success: {
                      iconTheme: {
                        primary: "#4ade80",
                        secondary: "#18181b",
                      },
                      style: {
                        background: "#18181b",
                        color: "#f3f4f6",
                      },
                    },
                    error: {
                      iconTheme: {
                        primary: "#f87171",
                        secondary: "#18181b",
                      },
                      style: {
                        background: "#18181b",
                        color: "#f3f4f6",
                      },
                    },
                  }}
                />
              </MusicPlayerProvider>
            </ReduxProvider>
          </GoogleOAuthProviderWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
