import type { Metadata } from "next";
import { Inter, Inria_Serif } from "next/font/google";
import "@/styles/globals.css";
import QueryProvider from "@/providers/QueryProvider";

const sans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: "variable",
});

const serif = Inria_Serif({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Cian Intl",
  description: "Generated by Cian Intl",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${sans.variable} ${serif.variable} antialiased`}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
